name: TeleportingGate
main: io.github.liuchibing.teleportinggate.TeleportingGate
version: "1.0.0"
api: ["1.0.0"]

load: POSTWORLD

author: liuchibing
description: Teleporting Gate Plugin for Nukkit
website: liuchibing.github.io

permissions: 
  teleportinggate.use:
    description: "use gate"
    default: true

commands:
  tpgate:
    description: "list the gates, set a gate or delete a gate"
    usage: "/tpgate [set name x y z] [del name]"
    permission: teleportinggate.use